spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/sfr-orquestrador-api
    username: user
    password: password

kafka:
  topic:
    package-delivery-topic: "package-delivery-topic"