/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sfr.sfr_orquestrador_api.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RequestStartedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2543841191648075175L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RequestStartedEvent\",\"namespace\":\"com.sfr.sfr_orquestrador_api.avro\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"correlationId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"weight\",\"type\":\"double\"},{\"name\":\"height\",\"type\":\"double\"},{\"name\":\"width\",\"type\":\"double\"},{\"name\":\"length\",\"type\":\"double\"},{\"name\":\"originZipCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"destinationZipCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cargoType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<RequestStartedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RequestStartedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RequestStartedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RequestStartedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RequestStartedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RequestStartedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RequestStartedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RequestStartedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RequestStartedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID orderId;
  private java.util.UUID correlationId;
  private double weight;
  private double height;
  private double width;
  private double length;
  private java.lang.String originZipCode;
  private java.lang.String destinationZipCode;
  private java.lang.String cargoType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RequestStartedEvent() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param correlationId The new value for correlationId
   * @param weight The new value for weight
   * @param height The new value for height
   * @param width The new value for width
   * @param length The new value for length
   * @param originZipCode The new value for originZipCode
   * @param destinationZipCode The new value for destinationZipCode
   * @param cargoType The new value for cargoType
   */
  public RequestStartedEvent(java.util.UUID orderId, java.util.UUID correlationId, java.lang.Double weight, java.lang.Double height, java.lang.Double width, java.lang.Double length, java.lang.String originZipCode, java.lang.String destinationZipCode, java.lang.String cargoType) {
    this.orderId = orderId;
    this.correlationId = correlationId;
    this.weight = weight;
    this.height = height;
    this.width = width;
    this.length = length;
    this.originZipCode = originZipCode;
    this.destinationZipCode = destinationZipCode;
    this.cargoType = cargoType;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return correlationId;
    case 2: return weight;
    case 3: return height;
    case 4: return width;
    case 5: return length;
    case 6: return originZipCode;
    case 7: return destinationZipCode;
    case 8: return cargoType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.util.UUID)value$; break;
    case 1: correlationId = (java.util.UUID)value$; break;
    case 2: weight = (java.lang.Double)value$; break;
    case 3: height = (java.lang.Double)value$; break;
    case 4: width = (java.lang.Double)value$; break;
    case 5: length = (java.lang.Double)value$; break;
    case 6: originZipCode = value$ != null ? value$.toString() : null; break;
    case 7: destinationZipCode = value$ != null ? value$.toString() : null; break;
    case 8: cargoType = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.util.UUID getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.util.UUID value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return The value of the 'correlationId' field.
   */
  public java.util.UUID getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * @param value the value to set.
   */
  public void setCorrelationId(java.util.UUID value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'weight' field.
   * @return The value of the 'weight' field.
   */
  public double getWeight() {
    return weight;
  }


  /**
   * Sets the value of the 'weight' field.
   * @param value the value to set.
   */
  public void setWeight(double value) {
    this.weight = value;
  }

  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public double getHeight() {
    return height;
  }


  /**
   * Sets the value of the 'height' field.
   * @param value the value to set.
   */
  public void setHeight(double value) {
    this.height = value;
  }

  /**
   * Gets the value of the 'width' field.
   * @return The value of the 'width' field.
   */
  public double getWidth() {
    return width;
  }


  /**
   * Sets the value of the 'width' field.
   * @param value the value to set.
   */
  public void setWidth(double value) {
    this.width = value;
  }

  /**
   * Gets the value of the 'length' field.
   * @return The value of the 'length' field.
   */
  public double getLength() {
    return length;
  }


  /**
   * Sets the value of the 'length' field.
   * @param value the value to set.
   */
  public void setLength(double value) {
    this.length = value;
  }

  /**
   * Gets the value of the 'originZipCode' field.
   * @return The value of the 'originZipCode' field.
   */
  public java.lang.String getOriginZipCode() {
    return originZipCode;
  }


  /**
   * Sets the value of the 'originZipCode' field.
   * @param value the value to set.
   */
  public void setOriginZipCode(java.lang.String value) {
    this.originZipCode = value;
  }

  /**
   * Gets the value of the 'destinationZipCode' field.
   * @return The value of the 'destinationZipCode' field.
   */
  public java.lang.String getDestinationZipCode() {
    return destinationZipCode;
  }


  /**
   * Sets the value of the 'destinationZipCode' field.
   * @param value the value to set.
   */
  public void setDestinationZipCode(java.lang.String value) {
    this.destinationZipCode = value;
  }

  /**
   * Gets the value of the 'cargoType' field.
   * @return The value of the 'cargoType' field.
   */
  public java.lang.String getCargoType() {
    return cargoType;
  }


  /**
   * Sets the value of the 'cargoType' field.
   * @param value the value to set.
   */
  public void setCargoType(java.lang.String value) {
    this.cargoType = value;
  }

  /**
   * Creates a new RequestStartedEvent RecordBuilder.
   * @return A new RequestStartedEvent RecordBuilder
   */
  public static com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder newBuilder() {
    return new com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder();
  }

  /**
   * Creates a new RequestStartedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RequestStartedEvent RecordBuilder
   */
  public static com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder newBuilder(com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder other) {
    if (other == null) {
      return new com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder();
    } else {
      return new com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RequestStartedEvent RecordBuilder by copying an existing RequestStartedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RequestStartedEvent RecordBuilder
   */
  public static com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder newBuilder(com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent other) {
    if (other == null) {
      return new com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder();
    } else {
      return new com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RequestStartedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RequestStartedEvent>
    implements org.apache.avro.data.RecordBuilder<RequestStartedEvent> {

    private java.util.UUID orderId;
    private java.util.UUID correlationId;
    private double weight;
    private double height;
    private double width;
    private double length;
    private java.lang.String originZipCode;
    private java.lang.String destinationZipCode;
    private java.lang.String cargoType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[1].schema(), other.correlationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.weight)) {
        this.weight = data().deepCopy(fields()[2].schema(), other.weight);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.width)) {
        this.width = data().deepCopy(fields()[4].schema(), other.width);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.length)) {
        this.length = data().deepCopy(fields()[5].schema(), other.length);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.originZipCode)) {
        this.originZipCode = data().deepCopy(fields()[6].schema(), other.originZipCode);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.destinationZipCode)) {
        this.destinationZipCode = data().deepCopy(fields()[7].schema(), other.destinationZipCode);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.cargoType)) {
        this.cargoType = data().deepCopy(fields()[8].schema(), other.cargoType);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing RequestStartedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[1].schema(), other.correlationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.weight)) {
        this.weight = data().deepCopy(fields()[2].schema(), other.weight);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.width)) {
        this.width = data().deepCopy(fields()[4].schema(), other.width);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.length)) {
        this.length = data().deepCopy(fields()[5].schema(), other.length);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.originZipCode)) {
        this.originZipCode = data().deepCopy(fields()[6].schema(), other.originZipCode);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.destinationZipCode)) {
        this.destinationZipCode = data().deepCopy(fields()[7].schema(), other.destinationZipCode);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cargoType)) {
        this.cargoType = data().deepCopy(fields()[8].schema(), other.cargoType);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.util.UUID getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setOrderId(java.util.UUID value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * @return The value.
      */
    public java.util.UUID getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setCorrelationId(java.util.UUID value) {
      validate(fields()[1], value);
      this.correlationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * @return The value.
      */
    public double getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setWeight(double value) {
      validate(fields()[2], value);
      this.weight = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'weight' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearWeight() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public double getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setHeight(double value) {
      validate(fields()[3], value);
      this.height = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearHeight() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'width' field.
      * @return The value.
      */
    public double getWidth() {
      return width;
    }


    /**
      * Sets the value of the 'width' field.
      * @param value The value of 'width'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setWidth(double value) {
      validate(fields()[4], value);
      this.width = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'width' field has been set.
      * @return True if the 'width' field has been set, false otherwise.
      */
    public boolean hasWidth() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'width' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearWidth() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'length' field.
      * @return The value.
      */
    public double getLength() {
      return length;
    }


    /**
      * Sets the value of the 'length' field.
      * @param value The value of 'length'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setLength(double value) {
      validate(fields()[5], value);
      this.length = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'length' field has been set.
      * @return True if the 'length' field has been set, false otherwise.
      */
    public boolean hasLength() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'length' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearLength() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'originZipCode' field.
      * @return The value.
      */
    public java.lang.String getOriginZipCode() {
      return originZipCode;
    }


    /**
      * Sets the value of the 'originZipCode' field.
      * @param value The value of 'originZipCode'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setOriginZipCode(java.lang.String value) {
      validate(fields()[6], value);
      this.originZipCode = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'originZipCode' field has been set.
      * @return True if the 'originZipCode' field has been set, false otherwise.
      */
    public boolean hasOriginZipCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'originZipCode' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearOriginZipCode() {
      originZipCode = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'destinationZipCode' field.
      * @return The value.
      */
    public java.lang.String getDestinationZipCode() {
      return destinationZipCode;
    }


    /**
      * Sets the value of the 'destinationZipCode' field.
      * @param value The value of 'destinationZipCode'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setDestinationZipCode(java.lang.String value) {
      validate(fields()[7], value);
      this.destinationZipCode = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'destinationZipCode' field has been set.
      * @return True if the 'destinationZipCode' field has been set, false otherwise.
      */
    public boolean hasDestinationZipCode() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'destinationZipCode' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearDestinationZipCode() {
      destinationZipCode = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'cargoType' field.
      * @return The value.
      */
    public java.lang.String getCargoType() {
      return cargoType;
    }


    /**
      * Sets the value of the 'cargoType' field.
      * @param value The value of 'cargoType'.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder setCargoType(java.lang.String value) {
      validate(fields()[8], value);
      this.cargoType = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'cargoType' field has been set.
      * @return True if the 'cargoType' field has been set, false otherwise.
      */
    public boolean hasCargoType() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'cargoType' field.
      * @return This builder.
      */
    public com.sfr.sfr_orquestrador_api.avro.RequestStartedEvent.Builder clearCargoType() {
      cargoType = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RequestStartedEvent build() {
      try {
        RequestStartedEvent record = new RequestStartedEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.util.UUID) defaultValue(fields()[0]);
        record.correlationId = fieldSetFlags()[1] ? this.correlationId : (java.util.UUID) defaultValue(fields()[1]);
        record.weight = fieldSetFlags()[2] ? this.weight : (java.lang.Double) defaultValue(fields()[2]);
        record.height = fieldSetFlags()[3] ? this.height : (java.lang.Double) defaultValue(fields()[3]);
        record.width = fieldSetFlags()[4] ? this.width : (java.lang.Double) defaultValue(fields()[4]);
        record.length = fieldSetFlags()[5] ? this.length : (java.lang.Double) defaultValue(fields()[5]);
        record.originZipCode = fieldSetFlags()[6] ? this.originZipCode : (java.lang.String) defaultValue(fields()[6]);
        record.destinationZipCode = fieldSetFlags()[7] ? this.destinationZipCode : (java.lang.String) defaultValue(fields()[7]);
        record.cargoType = fieldSetFlags()[8] ? this.cargoType : (java.lang.String) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RequestStartedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RequestStartedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RequestStartedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RequestStartedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










