/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sfr.sfr_worker_region.infrastructure.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RegionDefinedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8713039765782228259L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RegionDefinedEvent\",\"namespace\":\"com.sfr.sfr_worker_region.infrastructure.kafka.avro\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"correlationId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"region\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"cubedWeight\",\"type\":\"double\"},{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<RegionDefinedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RegionDefinedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RegionDefinedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RegionDefinedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RegionDefinedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RegionDefinedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RegionDefinedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RegionDefinedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RegionDefinedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID orderId;
  private java.util.UUID correlationId;
  private java.lang.String region;
  private double cubedWeight;
  private java.lang.String status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RegionDefinedEvent() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param correlationId The new value for correlationId
   * @param region The new value for region
   * @param cubedWeight The new value for cubedWeight
   * @param status The new value for status
   */
  public RegionDefinedEvent(java.util.UUID orderId, java.util.UUID correlationId, java.lang.String region, java.lang.Double cubedWeight, java.lang.String status) {
    this.orderId = orderId;
    this.correlationId = correlationId;
    this.region = region;
    this.cubedWeight = cubedWeight;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return correlationId;
    case 2: return region;
    case 3: return cubedWeight;
    case 4: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.util.UUID)value$; break;
    case 1: correlationId = (java.util.UUID)value$; break;
    case 2: region = value$ != null ? value$.toString() : null; break;
    case 3: cubedWeight = (java.lang.Double)value$; break;
    case 4: status = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.util.UUID getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.util.UUID value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'correlationId' field.
   * @return The value of the 'correlationId' field.
   */
  public java.util.UUID getCorrelationId() {
    return correlationId;
  }


  /**
   * Sets the value of the 'correlationId' field.
   * @param value the value to set.
   */
  public void setCorrelationId(java.util.UUID value) {
    this.correlationId = value;
  }

  /**
   * Gets the value of the 'region' field.
   * @return The value of the 'region' field.
   */
  public java.lang.String getRegion() {
    return region;
  }


  /**
   * Sets the value of the 'region' field.
   * @param value the value to set.
   */
  public void setRegion(java.lang.String value) {
    this.region = value;
  }

  /**
   * Gets the value of the 'cubedWeight' field.
   * @return The value of the 'cubedWeight' field.
   */
  public double getCubedWeight() {
    return cubedWeight;
  }


  /**
   * Sets the value of the 'cubedWeight' field.
   * @param value the value to set.
   */
  public void setCubedWeight(double value) {
    this.cubedWeight = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Creates a new RegionDefinedEvent RecordBuilder.
   * @return A new RegionDefinedEvent RecordBuilder
   */
  public static com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder newBuilder() {
    return new com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder();
  }

  /**
   * Creates a new RegionDefinedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RegionDefinedEvent RecordBuilder
   */
  public static com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder newBuilder(com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder other) {
    if (other == null) {
      return new com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder();
    } else {
      return new com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RegionDefinedEvent RecordBuilder by copying an existing RegionDefinedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RegionDefinedEvent RecordBuilder
   */
  public static com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder newBuilder(com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent other) {
    if (other == null) {
      return new com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder();
    } else {
      return new com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RegionDefinedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RegionDefinedEvent>
    implements org.apache.avro.data.RecordBuilder<RegionDefinedEvent> {

    private java.util.UUID orderId;
    private java.util.UUID correlationId;
    private java.lang.String region;
    private double cubedWeight;
    private java.lang.String status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[1].schema(), other.correlationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.region)) {
        this.region = data().deepCopy(fields()[2].schema(), other.region);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.cubedWeight)) {
        this.cubedWeight = data().deepCopy(fields()[3].schema(), other.cubedWeight);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing RegionDefinedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[1].schema(), other.correlationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.region)) {
        this.region = data().deepCopy(fields()[2].schema(), other.region);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cubedWeight)) {
        this.cubedWeight = data().deepCopy(fields()[3].schema(), other.cubedWeight);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.util.UUID getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder setOrderId(java.util.UUID value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * @return The value.
      */
    public java.util.UUID getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder setCorrelationId(java.util.UUID value) {
      validate(fields()[1], value);
      this.correlationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'region' field.
      * @return The value.
      */
    public java.lang.String getRegion() {
      return region;
    }


    /**
      * Sets the value of the 'region' field.
      * @param value The value of 'region'.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder setRegion(java.lang.String value) {
      validate(fields()[2], value);
      this.region = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'region' field has been set.
      * @return True if the 'region' field has been set, false otherwise.
      */
    public boolean hasRegion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'region' field.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder clearRegion() {
      region = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'cubedWeight' field.
      * @return The value.
      */
    public double getCubedWeight() {
      return cubedWeight;
    }


    /**
      * Sets the value of the 'cubedWeight' field.
      * @param value The value of 'cubedWeight'.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder setCubedWeight(double value) {
      validate(fields()[3], value);
      this.cubedWeight = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'cubedWeight' field has been set.
      * @return True if the 'cubedWeight' field has been set, false otherwise.
      */
    public boolean hasCubedWeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'cubedWeight' field.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder clearCubedWeight() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder setStatus(java.lang.String value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.sfr.sfr_worker_region.infrastructure.kafka.avro.RegionDefinedEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RegionDefinedEvent build() {
      try {
        RegionDefinedEvent record = new RegionDefinedEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.util.UUID) defaultValue(fields()[0]);
        record.correlationId = fieldSetFlags()[1] ? this.correlationId : (java.util.UUID) defaultValue(fields()[1]);
        record.region = fieldSetFlags()[2] ? this.region : (java.lang.String) defaultValue(fields()[2]);
        record.cubedWeight = fieldSetFlags()[3] ? this.cubedWeight : (java.lang.Double) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RegionDefinedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RegionDefinedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RegionDefinedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RegionDefinedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










